### ISSUE TITLE
0.5.0 Roadmap

### ISSUE THREAD

**Issue by nanliu** [voxpupuli/puppet-archive#62]
#55 identified a memory usage problem for archive module. Our goal for 0.5.0 is to resolve this problem and address the following issue.

- [x] default ruby provider should use net::http with streaming (see #124).
- [x] faraday should no longer be a requirement for puppet agents #60. (for now remain a requirement for puppet master for the define types/functions see #124)
- [x] faraday can be used as an alternative provider to support migration.
- [x] linux system can use alternative default providers #61.
- [x] migrate to puppet community travis config. #82 

Since this requires several changes, master will be unstable until we resolve them. Please feel free to discuss or comment on this issue if you have any input.

**Comment by nibalizer** [comment]
This is pretty sweet. I'm excited to see open development and roadmap. Are there any testing needs you have that travis can't provide? That's kindof my current kick. @igalic mentioned that we may be hitting max_concurrent travis testing now.

**Comment by nanliu** [comment]
Travis is sufficient for now, do we have a standard gemfile/.travis.yml config?

**Comment by nibalizer** [comment]
https://github.com/puppet-community/puppet-extlib has a good Gemfile, Rakefile, .travis.yml
That also provides hooks for you to setup blacksmith deploys of archive. I'm not sure if you want to keep publishing this to your own namespace or use forge.puppetlabs.com/puppet.

The secure: line comes from:
https://github.com/puppet-community/plumbing/blob/master/share/travis_secrets

**Comment by jairojunior** [comment]
@nanliu can you publish a 0.3.1 version in forge with archive::nexus support?

**Comment by nibalizer** [comment]
https://github.com/puppet-community/puppet-archive/pull/64 would enable the bits to enable push button deploys, which would open the door to a 3.1

**Comment by MartinMeinhold** [comment]
> @nanliu can you publish a 0.3.1 version in forge with archive::nexus support?

+1

**Comment by logicminds** [comment]
+1 for not having to install faraday on every system, especially when no internet access is available or a local ruby gems server.  I have been working on a hacked version that bundles the gems inside the files directory.

**Comment by jyaworski** [comment]
#82 brought us up to date with https://github.com/puppet-community/modulesync_config so we're in line with some other modules and their styling/methodology.

**Comment by jyaworski** [comment]
Also, @nanliu should this issue be for 0.5.0 now?

**Comment by nanliu** [comment]
@jyaworski, issue updated, looking for volunteers to test:

- [ ] Windows platform (review & test #124).
- [ ] go function (changes in progress)
- [ ] artifactory function (changes in progress)

**Comment by jyaworski** [comment]
Merged #124
